version: 2.1

orbs:
  docker: circleci/docker@2.4.0

commands:
  build:
    parameters:
      dir:
        type: string
      image_name:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
          docker-context: <<parameters.dir>>
          path: <<parameters.dir>>
          image: $DOCKER_USER/demo-<<parameters.image_name>>
          tag: $CIRCLE_BUILD_NUM

  publish:
    parameters:
      image_name:
        type: string
    steps:
      - docker/check:
          docker-password: DOCKER_PASS
          docker-username: DOCKER_USER
      - docker/push:
          image: $DOCKER_USER/demo-<<parameters.image_name>>
          tag: $CIRCLE_BUILD_NUM

jobs:
  build_job:
    executor: docker/docker
    steps:
      - build:
          dir: .
          image_name: todo-app-django

  publish_job:
    executor: docker/docker
    steps:
      - build:
          dir: .
          image_name: todo-app-django
      - publish:
          image_name: todo-app-django

workflows:
  build_and_publish_workflow:
    jobs:
      - build_job:
          filters:
            branches:
              ignore: main
      - publish_job:
          filters:
            branches:
              only: main
