apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: django-todo-app
  namespace: django-todo-app
  labels: 
    app: django-todo-app
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: django-todo-app
  template:
    metadata:
      labels:
        app: django-todo-app
    spec:   
      containers:   
      - name: django-todo-app
        image: dipanshu13/django-todo:v1
        ports:
        - containerPort: 8000